version 7.0

set expandtab
set tabstop=4
set shiftwidth=4

if ($TERM != "linux")
    set ttytype=xterm
endif

set autoindent
set noautowrite
set nobackup
set nocompatible

set dictionary=/usr/share/dict/words,$HOME/.words

" magic: use some magic in search patterns
set magic

set showcmd
set wildchar=<TAB>

map ,v :e ~/.vimrc<CR>
map ,u :source ~/.vimrc<CR>

map ,X :r!date +\%Y-\%m-\%d<CR>I<br>[<ESC>A]<ESC>
vmap ,dr :!tr A-Za-z N-ZA-Mn-za-m

syntax on

map # :e#<CR>

" For viewing Word files inline
autocmd BufReadPre *.doc set ro
autocmd BufReadPre *.doc set hlsearch!
autocmd BufReadPost *.doc %!antiword "%"

autocmd BufEnter ~/.mutt/** set syntax=muttrc
set background=dark

source ~/.vim/dev.vimrc

call pathogen#helptags()
call pathogen#runtime_append_all_bundles()
