autoload -Uz compinit
compinit
setopt appendhistory autocd extendedglob
zstyle :compinstall filename "$HOME/.zshrc"
zstyle ':completion:*' completer _expand _complete


export HISTFILE="$HOME/.history"
export HISTSIZE=1000
export SAVEHIST=1000
export FULLNAME="`grep $USER: /etc/passwd | cut -d: -f5`"
export DOMAIN=`hostname -d`
export REPLYTO="$FULLNAME <$USER@$DOMAIN>"
export PROMPT="%m:%~%# "
export RPROMPT=" %t"
export SPROMPT="you mean, '%r' instead of '%R'? [nyae] "
export TERM=`tset - -Q`
#export TERM=linux
export LYNX_TEMP_SPACE=$TMPDIR
export EDITOR=vim
export CVS_RSH=ssh

export CC=gcc
export CFLAGS="-O2 -mtune=native"
export CXXFLAGS="$CFLAGS -fvisibility-inlines-hidden"
export RSYNC_RSH=ssh
export GEM_HOME=$HOME/.gems
export PATH=$GEM_HOME/bin:$PATH
export GEM_PATH=`gem env gempath`
watch=all

alias fgrep='fgrep --color=auto'

export TMPDIR=/tmp/$USER
if [ ! -d $TMPDIR ]
then
	rm -rf ~/tmp
	mkdir $TMPDIR; chmod 700 $TMPDIR
	ln -sf $TMPDIR ~/tmp
fi

trap 'clear' 0 1

chpwd ()
{
	[[ -t 1 ]] || return
	case $TERM in
		sun-cmd) print -Pn "\e]l%~\e\\"
			 ;;
		xterm) print -Pn "\e]2;%~\a"
		     ;;
		linux) print -Pn "\e]2;%~\a"
		     ;;
	esac
}

umask 077
ulimit -c 0

export ZSHRCDIR=$HOME/.zsh
if [ -d $ZSHRCDIR ]; then
	for file in `find $ZSHRCDIR/ -type f -name 'z*'`; do
		source $file
	done
fi

#bday=`bday`
#if [ "$bday" = "" ]; then
#else
#echo "[1m[35mBirthday(s) today:[m"
#echo $bday
#fi

export WNHOME=/usr/local/WordNet-3.0
export PATH=$WNHOME/bin:$PATH
export PATH=$GEM_HOME/bin:$PATH

if [ -f $HOME/.motd ]; then
	cat $HOME/.motd
fi

RSYNCEXCLUDESFILE=$HOME/.rsync-exclude
# Nostalgia stuff
#gate=`echo "(- \`date +%s\` +  \`date --date 2000-02-13 +%s\`)/86400" | bc`
#echo "			[33m[1m[5m$gate[m days to go for GATE!"

# From http://web.davidfaure.fr/scripts/cd_function
which findup &>/dev/null
if [ "x$?" = "x0" ]; then
function cd() {
  # Use this for bash:
  # builtin cd "$*"
  # Use this for zsh (otherwise just "cd" doesn't work) :
  builtin cd $*
  _f=`findup .my-setup`
  if test -n "$_f" -a "$_lastf" != "$_f"; then
    echo "Loading $_f"
    _lastf="$_f"
    source "$_f"
  fi
}
else
echo "No findup in path!"
fi
